idf_component_register(
    SRCS
        "main.cpp"
        "startup_anim.cpp"
        "wifi_screen.cpp"
        "wifi_manager.cpp"
        "time_manager.cpp"
        "status_bar.cpp"
        "time_screen.cpp"
        "api_server.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        m5stack_tab5
        lvgl
        mooncake
        mooncake_log
        smooth_ui_toolkit
        esp_wifi
        esp_event
        nvs_flash
        esp_netif
        mdns
        esp_http_server
        json
)
