"""
Functional tests for the events and miscellaneous API endpoints.

Covers:
  - GET/DELETE /api/events — operational event log
  - GET /api/display/brightness
  - GET /api/preferences
  - GET /api/health
  - GET /api/status
  - GET /api/time
  - GET /api/wifi
  - GET /api/info

Prerequisites:
  - Device reachable at ARCTIC_URL (default http://arctic.local)
  - ARCTIC_API_KEY env var set
"""

import os
import time

import pytest
import requests
from pathlib import Path

# Load .env from repo root if present (local dev)
_env_file = Path(__file__).resolve().parent.parent.parent / ".env"
if _env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(_env_file)

BASE_URL = os.environ.get("ARCTIC_URL", "http://arctic.local")
API_KEY = os.environ.get("ARCTIC_API_KEY")


def _headers():
    h = {}
    if API_KEY:
        h["X-API-Key"] = API_KEY
    return h


def _get(path, **kwargs):
    return requests.get(f"{BASE_URL}{path}", headers=_headers(), timeout=10, **kwargs)


def _post(path, json=None, **kwargs):
    return requests.post(f"{BASE_URL}{path}", headers=_headers(), json=json, timeout=10, **kwargs)


def _delete(path):
    return requests.delete(f"{BASE_URL}{path}", headers=_headers(), timeout=10)


@pytest.fixture(scope="module", autouse=True)
def _check_prerequisites():
    if not API_KEY:
        pytest.skip("ARCTIC_API_KEY not set")
    try:
        r = requests.get(f"{BASE_URL}/api/health", timeout=5)
        r.raise_for_status()
    except Exception as e:
        pytest.skip(f"Device not reachable at {BASE_URL}: {e}")


# ── Events API ────────────────────────────────────────────────────────────


class TestEventsAPI:
    """GET/DELETE /api/events — operational event log."""

    def test_events_returns_200(self):
        r = _get("/api/events")
        assert r.status_code == 200

    def test_events_response_structure(self):
        data = _get("/api/events").json()
        assert "total" in data
        assert "events" in data
        assert isinstance(data["events"], list)
        assert isinstance(data["total"], int)

    def test_event_entry_structure(self):
        """Each event should have type, timestamp, uptime_ms, payload."""
        data = _get("/api/events").json()
        if len(data["events"]) == 0:
            pytest.skip("No events on device")
        evt = data["events"][0]
        for field in ["type", "timestamp", "uptime_ms", "payload"]:
            assert field in evt, f"Missing event field: {field}"

    def test_event_type_is_string(self):
        """Event type should be a known string."""
        valid_types = {
            "system_start", "power_on", "power_off", "mode_changed",
            "setpoint_changed", "compressor_on", "compressor_off",
            "fan_on", "fan_off", "pump_on", "pump_off",
            "aux_heater_on", "aux_heater_off", "defrost_start", "defrost_end",
            "error_appeared", "error_cleared", "connected", "disconnected",
        }
        data = _get("/api/events").json()
        for evt in data["events"]:
            assert evt["type"] in valid_types, f"Unknown event type: {evt['type']}"

    def test_events_total_matches_array_length(self):
        """total field should match or exceed the events array length."""
        data = _get("/api/events").json()
        # total is the ring buffer count, events is what was returned
        assert data["total"] >= len(data["events"])

    def test_clear_events(self):
        """DELETE /api/events should clear the event log."""
        r = _delete("/api/events")
        assert r.status_code == 200
        data = r.json()
        assert data["success"] is True

    def test_events_empty_after_clear(self):
        """After clearing, the event count should be 0 or very small."""
        _delete("/api/events")
        time.sleep(0.3)
        data = _get("/api/events").json()
        # Some events may be generated by the clear itself or background tasks
        assert data["total"] < 5


# ── Health API ────────────────────────────────────────────────────────────


class TestHealthAPI:
    """GET /api/health — health check."""

    def test_health_returns_ok(self):
        data = _get("/api/health").json()
        assert data["status"] == "ok"

    def test_health_has_uptime(self):
        data = _get("/api/health").json()
        assert "uptime_ms" in data
        assert data["uptime_ms"] > 0

    def test_health_uptime_increases(self):
        """Two consecutive calls should show increasing uptime."""
        t1 = _get("/api/health").json()["uptime_ms"]
        time.sleep(0.2)
        t2 = _get("/api/health").json()["uptime_ms"]
        assert t2 > t1


# ── Status API ────────────────────────────────────────────────────────────


class TestStatusAPI:
    """GET /api/status — full device status."""

    def test_status_returns_200(self):
        r = _get("/api/status")
        assert r.status_code == 200

    def test_status_has_device_name(self):
        data = _get("/api/status").json()
        assert "device" in data
        assert isinstance(data["device"], str)

    def test_status_has_wifi_section(self):
        data = _get("/api/status").json()
        assert "wifi" in data
        wifi = data["wifi"]
        assert "state" in wifi
        assert wifi["state"] in [
            "not_initialized", "disconnected", "connecting", "connected", "error"
        ]

    def test_status_has_time_section(self):
        data = _get("/api/status").json()
        assert "time" in data
        assert "local" in data["time"]

    def test_status_uptime_positive(self):
        data = _get("/api/status").json()
        assert data["uptime_ms"] > 0


# ── Time API ──────────────────────────────────────────────────────────────


class TestTimeAPI:
    """GET /api/time — time information."""

    def test_time_returns_200(self):
        r = _get("/api/time")
        assert r.status_code == 200

    def test_time_has_epoch(self):
        data = _get("/api/time").json()
        assert "epoch" in data
        assert isinstance(data["epoch"], (int, float))

    def test_time_has_formats(self):
        """Should have 24h, 12h, date, and iso formats."""
        data = _get("/api/time").json()
        assert "time_24h" in data
        assert "time_12h" in data
        assert "date" in data
        assert "iso" in data

    def test_time_has_timezone(self):
        data = _get("/api/time").json()
        assert "timezone" in data
        assert isinstance(data["timezone"], str)

    def test_time_has_ntp_synced(self):
        data = _get("/api/time").json()
        assert "ntp_synced" in data
        assert isinstance(data["ntp_synced"], bool)


# ── WiFi API ──────────────────────────────────────────────────────────────


class TestWiFiAPI:
    """GET /api/wifi — WiFi connection status."""

    def test_wifi_returns_200(self):
        r = _get("/api/wifi")
        assert r.status_code == 200

    def test_wifi_has_state(self):
        data = _get("/api/wifi").json()
        assert "state" in data
        assert data["state"] in [
            "not_initialized", "disconnected", "connecting", "connected", "error"
        ]

    def test_wifi_has_connected_flag(self):
        data = _get("/api/wifi").json()
        assert "connected" in data
        assert isinstance(data["connected"], bool)

    def test_wifi_connected_has_details(self):
        """When connected, should have SSID, IP, RSSI, hostname."""
        data = _get("/api/wifi").json()
        if not data["connected"]:
            pytest.skip("WiFi not connected")
        assert "ssid" in data
        assert "ip" in data
        assert "rssi" in data
        assert isinstance(data["rssi"], int)
        assert data["rssi"] < 0  # RSSI is always negative dBm


# ── Info API ──────────────────────────────────────────────────────────────


class TestInfoAPI:
    """GET /api/info — device information."""

    def test_info_returns_200(self):
        r = _get("/api/info")
        assert r.status_code == 200

    def test_info_has_version(self):
        data = _get("/api/info").json()
        assert "version" in data
        assert isinstance(data["version"], str)
        # Version should be in semver-ish format (e.g., "2.4.0")
        parts = data["version"].split(".")
        assert len(parts) >= 2

    def test_info_has_platform(self):
        data = _get("/api/info").json()
        assert data["platform"] == "ESP32-P4"

    def test_info_has_memory_stats(self):
        data = _get("/api/info").json()
        assert "free_heap" in data
        assert "min_free_heap" in data
        assert data["free_heap"] > 0
        assert data["min_free_heap"] > 0
        # min_free_heap should always be <= free_heap
        assert data["min_free_heap"] <= data["free_heap"]

    def test_info_has_api_version(self):
        data = _get("/api/info").json()
        assert "api_version" in data


# ── Display / Preferences ─────────────────────────────────────────────────


class TestDisplayBrightness:
    """GET /api/display/brightness."""

    def test_brightness_returns_200(self):
        r = _get("/api/display/brightness")
        assert r.status_code == 200

    def test_brightness_value(self):
        data = _get("/api/display/brightness").json()
        assert "brightness" in data
        assert isinstance(data["brightness"], int)
        assert 0 <= data["brightness"] <= 100


class TestPreferences:
    """GET /api/preferences — user preferences."""

    def test_preferences_returns_200(self):
        r = _get("/api/preferences")
        assert r.status_code == 200

    def test_preferences_has_all_fields(self):
        data = _get("/api/preferences").json()
        for field in ["demo_mode", "temp_unit", "brightness", "language",
                       "format_24h", "timezone"]:
            assert field in data, f"Missing preference: {field}"

    def test_preferences_demo_mode_is_bool(self):
        data = _get("/api/preferences").json()
        assert isinstance(data["demo_mode"], bool)

    def test_preferences_temp_unit_valid(self):
        data = _get("/api/preferences").json()
        assert data["temp_unit"] in ("celsius", "fahrenheit")

    def test_preferences_language_is_string(self):
        data = _get("/api/preferences").json()
        assert isinstance(data["language"], str)
        assert len(data["language"]) > 0

    def test_preferences_format_24h_is_bool(self):
        data = _get("/api/preferences").json()
        assert isinstance(data["format_24h"], bool)


# ── Time Config API ───────────────────────────────────────────────────────


class TestTimeConfig:
    """GET/POST /api/time/config — timezone and time format configuration."""

    def test_get_time_config_returns_200(self):
        r = _get("/api/time/config")
        assert r.status_code == 200

    def test_time_config_has_timezone(self):
        data = _get("/api/time/config").json()
        assert "timezone" in data
        assert isinstance(data["timezone"], str)

    def test_time_config_has_format_24h(self):
        data = _get("/api/time/config").json()
        assert "format_24h" in data
        assert isinstance(data["format_24h"], bool)

    def test_time_config_has_synced(self):
        data = _get("/api/time/config").json()
        assert "synced" in data
        assert isinstance(data["synced"], bool)

    def test_set_and_restore_timezone(self):
        """POST a different timezone, verify it took, then restore original."""
        # Read original
        original = _get("/api/time/config").json()
        orig_tz = original["timezone"]

        # Set a different timezone
        test_tz = "PST8PDT,M3.2.0,M11.1.0" if orig_tz != "PST8PDT,M3.2.0,M11.1.0" else "UTC0"
        r = _post("/api/time/config", json={"timezone": test_tz})
        assert r.status_code == 200
        assert r.json().get("success") is True

        # Verify it changed
        updated = _get("/api/time/config").json()
        assert updated["timezone"] == test_tz

        # Restore original
        r = _post("/api/time/config", json={"timezone": orig_tz})
        assert r.status_code == 200
        restored = _get("/api/time/config").json()
        assert restored["timezone"] == orig_tz

    def test_set_and_restore_format_24h(self):
        """Toggle format_24h, verify, then restore."""
        original = _get("/api/time/config").json()
        orig_fmt = original["format_24h"]

        # Toggle
        r = _post("/api/time/config", json={"format_24h": not orig_fmt})
        assert r.status_code == 200

        updated = _get("/api/time/config").json()
        assert updated["format_24h"] is (not orig_fmt)

        # Restore
        _post("/api/time/config", json={"format_24h": orig_fmt})
        restored = _get("/api/time/config").json()
        assert restored["format_24h"] is orig_fmt


# ── OTA Status API ────────────────────────────────────────────────────────


class TestOtaStatus:
    """GET /api/ota/status — read-only OTA state check."""

    def test_ota_status_returns_200(self):
        r = _get("/api/ota/status")
        assert r.status_code == 200

    def test_ota_status_is_idle(self):
        """When no update is in progress, state should be idle."""
        data = _get("/api/ota/status").json()
        assert data["state"] == "idle"

    def test_ota_status_progress_zero(self):
        data = _get("/api/ota/status").json()
        assert data["progress"] == 0

    def test_ota_status_has_current_version(self):
        data = _get("/api/ota/status").json()
        assert "current_version" in data
        assert isinstance(data["current_version"], str)
        # Should be semver-ish
        parts = data["current_version"].split(".")
        assert len(parts) >= 2

    def test_ota_status_has_download_fields(self):
        data = _get("/api/ota/status").json()
        assert "bytes_downloaded" in data
        assert isinstance(data["bytes_downloaded"], int)
        assert "total_bytes" in data
        assert isinstance(data["total_bytes"], int)

    def test_ota_status_state_is_valid_enum(self):
        data = _get("/api/ota/status").json()
        valid_states = {"idle", "uploading", "downloading", "verifying",
                        "ready_to_reboot", "failed"}
        assert data["state"] in valid_states


# ── Time Sync API ─────────────────────────────────────────────────────────


class TestTimeSync:
    """POST /api/time/sync — trigger NTP synchronization."""

    def test_time_sync_returns_200(self):
        """Triggering NTP sync should return success."""
        r = _post("/api/time/sync")
        assert r.status_code == 200
        data = r.json()
        assert data.get("success") is True
