"""
Test: Event Log Screen

Navigates to the event log screen and verifies empty state, title,
close button, and clear functionality.

Note: Events are generated internally by state changes — there is no
test injection endpoint. We can test the empty state after clearing,
and the system_start event that's always present.
"""

import time
import pytest
from device_client import DeviceClient

UI_SETTLE = 1.5


def _open_event_log(device: DeviceClient):
    """Navigate from main to the event log screen."""
    device.click(tag="nav_events")
    assert device.wait_for_screen("event_log", timeout=5.0), \
        f"Expected 'event_log' screen, got '{device.screen}'"
    time.sleep(0.5)


def _close_event_log(device: DeviceClient):
    """Return to the Home (main) tab via the persistent nav bar."""
    device.click(tag="nav_home")
    assert device.wait_for_screen("main", timeout=5.0), \
        f"Expected 'main' screen after close, got '{device.screen}'"


# =========================================================================
# Navigation
# =========================================================================

class TestEventLogNavigation:
    """Open/close event log screen from the main screen footer."""

    def test_open_event_log_screen(self, device: DeviceClient):
        """Clicking the Events nav button opens the event log screen."""
        _open_event_log(device)

    def test_close_event_log_screen(self, device: DeviceClient):
        """Clicking the close button returns to the main screen."""
        _open_event_log(device)
        _close_event_log(device)


# =========================================================================
# Title & Layout
# =========================================================================

class TestEventLogTitle:
    """Verify the event log controls. The per-tab title/count header was
    removed in the persistent-nav shell (the nav bar labels the tab)."""

    def test_clear_button_present(self, device: DeviceClient):
        """The clear button should be visible."""
        _open_event_log(device)
        clear_btn = device.find_widget(tag="event_log_clear")
        assert clear_btn is not None, "Event log clear button not found"


# =========================================================================
# Empty State
# =========================================================================

class TestEventLogEmptyState:
    """Clear the event log and verify the empty-state message."""

    @pytest.fixture(autouse=True)
    def _restore_events(self, device: DeviceClient):
        """Let the test run; afterwards the system_start event will
        reappear on the next event (no explicit restore needed)."""
        yield

    def test_empty_state_after_clear(self, device: DeviceClient):
        """After clearing all events, the 'No events' message should appear."""
        _open_event_log(device)

        # Clear events
        device.click(tag="event_log_clear")
        time.sleep(1.0)

        # The empty-state label should now be visible
        empty = device.find_widget(tag="event_log_empty")
        assert empty is not None, "Empty-state label not found after clearing"
        # Text should be the i18n "No events recorded" string
        text = empty.text_en or empty.text
        assert "no events" in text.lower(), \
            f"Expected 'No events' message, got: {text!r}"

    def test_content_shows_events_after_clear(self, device: DeviceClient):
        """After clearing, the empty-state label should be shown (no count
        header exists in the persistent-nav shell)."""
        _open_event_log(device)

        device.click(tag="event_log_clear")
        time.sleep(1.0)

        empty = device.find_widget(tag="event_log_empty")
        assert empty is not None, \
            "Empty-state label not shown after clearing events"


# =========================================================================
# Event Display
# =========================================================================

class TestEventLogDisplay:
    """Verify events appear as card entries."""

    def test_system_start_event_present(self, device: DeviceClient):
        """Events generated by state changes appear in the log.

        The tab shell has no count header, so we generate activity (an error
        transition logs events) and assert content is present indirectly:
        the empty-state label must be absent."""
        # Generate events via an error set/clear transition.
        device.set_demo_fields(error1=0x0001)
        time.sleep(1.5)
        device.set_demo_fields(error1=0)
        time.sleep(1.5)

        _open_event_log(device)
        time.sleep(0.5)

        # If events exist, the "no events" empty-state label is not rendered.
        empty = device.find_widget(tag="event_log_empty")
        assert empty is None, \
            "Empty-state label present despite recent event activity"

    def test_events_via_api(self, device: DeviceClient):
        """The /api/events endpoint should return events matching the UI count."""
        resp = device.session.get(f"{device.base_url}/api/events")
        assert resp.status_code == 200
        data = resp.json()
        assert "total" in data, "Expected 'total' field in events response"
        assert isinstance(data["total"], int)
        # In demo mode after boot, we should have at least 1 event (system_start)
        assert data["total"] >= 0


# =========================================================================
# API Clear
# =========================================================================

class TestEventLogApiClear:
    """Verify the DELETE /api/events endpoint clears the log."""

    def test_clear_via_api(self, device: DeviceClient):
        """DELETE /api/events should clear, then GET should return total=0."""
        resp = device.session.delete(f"{device.base_url}/api/events")
        assert resp.status_code == 200

        resp = device.session.get(f"{device.base_url}/api/events")
        assert resp.status_code == 200
        data = resp.json()
        assert data["total"] == 0, \
            f"Expected 0 events after clear, got {data['total']}"

    def test_ui_reflects_api_clear(self, device: DeviceClient):
        """After clearing via API, the event log screen should show empty state."""
        device.session.delete(f"{device.base_url}/api/events")
        time.sleep(0.5)

        _open_event_log(device)
        time.sleep(1.0)

        empty = device.find_widget(tag="event_log_empty")
        assert empty is not None, \
            "Empty-state label not found after API clear"
