"""Regenerate home_icons.c: the home screen's component indicator icons.

The icons are simple SVGs (below) rendered to 8-bit alpha (LV_COLOR_FORMAT_A8)
images, so the firmware can tint each one with any accent colour via
image_recolor. Needs Playwright (Chromium) and Pillow:

    pip install playwright pillow && python -m playwright install chromium
    python main/fonts/regen_home_icons.py
"""
import io
import os

from PIL import Image
from playwright.sync_api import sync_playwright

SIZE = 30   # output size in px
SCALE = 4   # supersampling factor for smooth edges

ICONS = {
    "compressor": '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round">'
                  '<rect x="5" y="4" width="14" height="16" rx="4"/><path d="M9 9h6M9 12h6M9 15h6"/></svg>',
    "fan":        '<svg viewBox="0 0 24 24" fill="#fff"><circle cx="12" cy="12" r="2.2"/>'
                  '<path d="M12 10c-1-4 0-7 3-7 3 1 1 5-3 7z"/>'
                  '<path d="M13.8 13c3.8-1.4 6.8-.6 6.9 2.5-.6 3.1-4.6 1.4-6.9-2.5z"/>'
                  '<path d="M10.2 13c-2.8 3-5.8 3.8-7.3 1.1-.5-3.1 3.9-3.3 7.3-1.1z"/></svg>',
    "pump":       '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round">'
                  '<circle cx="11" cy="13" r="7"/><path d="M11 13l4-4M11 13l-3 4M11 13l-4-3"/><path d="M15 6h6"/></svg>',
    "heater":     '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
                  '<path d="M4 18l2-5 3 5 3-5 3 5 3-5 2 5"/><path d="M8 4c-1 2 1 3 0 5M12 4c-1 2 1 3 0 5M16 4c-1 2 1 3 0 5"/></svg>',
}


def render(page, svg):
    px = SIZE * SCALE
    page.set_content(f'<html><body style="margin:0;background:transparent">'
                     f'<div style="width:{px}px;height:{px}px">'
                     f'{svg.replace("<svg ", f"<svg width=\"{px}\" height=\"{px}\" ", 1)}</div></body></html>')
    png = page.locator("div").screenshot(omit_background=True)
    img = Image.open(io.BytesIO(png)).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    return img.getchannel("A").tobytes()


def main():
    out = [
        "// Generated by regen_home_icons.py. Do not edit by hand.",
        "// Home screen component indicator icons, 8-bit alpha (tint with image_recolor).",
        '#include "home_icons.h"',
        "",
    ]
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": SIZE * SCALE, "height": SIZE * SCALE})
        for name, svg in ICONS.items():
            data = render(page, svg)
            out.append(f"static const uint8_t {name}_map[] = {{")
            for row in range(SIZE):
                chunk = data[row * SIZE:(row + 1) * SIZE]
                out.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
            out.append("};")
            out.append("")
            out.append(f"const lv_image_dsc_t home_icon_{name} = {{")
            out.append("    .header = {")
            out.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
            out.append("        .cf = LV_COLOR_FORMAT_A8,")
            out.append(f"        .w = {SIZE},")
            out.append(f"        .h = {SIZE},")
            out.append(f"        .stride = {SIZE},")
            out.append("    },")
            out.append(f"    .data_size = sizeof({name}_map),")
            out.append(f"    .data = {name}_map,")
            out.append("};")
            out.append("")
        browser.close()
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "home_icons.c")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
